apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/results/platform"