#
# Copyright (C) 2025 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'
services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: iotgdevcloud/benchmark:latest
    container_name: metrics-collector
    privileged: true
    pid: host
    network_mode: "host"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - NPU_LOG=/tmp/results/npu_usage.csv
    volumes:
      - ${log_dir}:/tmp/results
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /sys/devices:/sys/devices
      - /dev/dri:/dev/dri:rw
      - /sys/class/drm:/sys/class/drm:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
    devices:
      - "/sys:/sys"
      - "/dev:/dev"
      - "/run:/run"
      - "/proc:/proc"
