#
# Copyright (C) 2025 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'
services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: benchmark:latest
    container_name: metrics-collector
    privileged: true
    network_mode: "host"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - NPU_LOG=/tmp/results/npu_usage.csv
    volumes:
      - ${log_dir}:/tmp/results
      - ${log_dir}/logs:/tmp/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /sys/devices:/sys/devices