#
# Copyright (C) 2025 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
version: '3'
services:
  platform:
    image: benchmark:platform
    container_name: platform
    privileged: true
    volumes:
      - $log_dir:/tmp/results
  igt:
    image: benchmark:igt
    container_name: igt
    privileged: true
    volumes:
      - $log_dir:/tmp/results
  npu-util:
    image: python:3.13-slim
    command: ["python3", "-u", "/tmp/npu_logger.py"]
    environment:
      - NPU_LOG=/tmp/results/npu_log.csv
    network_mode: "host"
    volumes:
      - /sys/devices:/sys/devices
      - $log_dir:/tmp/results
      - ${RETAIL_USE_CASE_ROOT:-..}/performance-tools/docker/npu-util/npu_logger.py:/tmp/npu_logger.py
  # xpum:
  #   image: benchmark:xpum
  #   container_name: xpum
  #   user: root
  #   privileged: true
  #   volumes:
  #     - $log_dir:/tmp/xpumdump/
  #     - /sys/firmware/acpi/tables/MCFG:/pcm/sys/firmware/acpi/tables/MCFG:ro 
  #     - /proc/bus/pci/:/pcm/proc/bus/pci/ 
  #     - /proc/sys/kernel/nmi_watchdog:/pcm/proc/sys/kernel/nmi_watchdog 
  #   environment:
  #     - XPUM_REST_NO_TLS=1
  #   devices:
  #     - /dev/dri:/dev/dri
  #     - /dev/cpu:/dev/cpu
