name: edge-video-performance-evaluation-tool
description: A generated Helm Chart for edge-video-performance-evaluation-tool from Skippbox Kompose
version: 3.2.0
apiVersion: v2
keywords:
  - edge-video-performance-evaluation-tool
sources:
home:
