name: Build docker images

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_benchmark:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
          - name: Make benchmark Docker images
            run: |
              cd docker && make build-benchmark
