name: Dispatch Update Submodule
on:
  push:
    branches:
      - main
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['intel-retail/automated-self-checkout']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GEN_PAT_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update-submodule
