name: Adds all issues to project board

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        with:
          project-url: https://github.com/orgs/intel-retail/projects/1
          github-token: ${{ secrets.GEN_PAT_TOKEN }}
