name: Send repository update event

on:
  push:
    branches:
      - main

jobs:
  trigger-module-update-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send module update event automated self checkout
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GEN_PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/intel-retail/automated-self-checkout/dispatches \
            -d '{"event_type":"dispatch-event"}'
