# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy_image_scan

on: 
  workflow_dispatch:
  pull_request: 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
    trivy_image_scan_platform:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: trivy_image_scan
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: main

        - name: Build an image from Dockerfile
          run: |
            echo "running make build platform benchmark"
            cd docker && make build-platform
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: 'benchmark:platform'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3.27.3
          with:
            sarif_file: 'trivy-results.sarif'

    trivy_image_scan_xpum:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: trivy_image_scan
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: main

        - name: Build an image from Dockerfile
          run: |
            echo "running make build xpum benchmark"
            cd docker && make build-xpum
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: 'benchmark:xpum'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3.27.3
          with:
            sarif_file: 'trivy-results.sarif'
    
    trivy_image_scan_igt:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: trivy_image_scan
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: main

        - name: Build an image from Dockerfile
          run: |
            echo "running make build igt benchmark"
            cd docker && make build-igt
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: 'benchmark:igt'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3.27.3
          with:
            sarif_file: 'trivy-results.sarif'